export enum IdType {
  CITIZENSHIP_CARD = 'CÉDULA DE CIUDADANÍA',
  FOREIGNER_ID = 'CÉDULA DE EXTRANJERÍA',
  IDENTITY_CARD = 'TARJETA DE IDENTIDAD',
  CIVIL_REGISTRATION = 'REGISTRO CIVIL',
  PASSPORT = 'PASAPORTE',
  SPECIAL_RESIDENCE_PERMIT = 'PERMISO ESPECIAL DE PERMANENCIA',
  TEMPORARY_PROTECTION_PERMIT = 'PERMISO POR PROTECCIÓN TEMPORAL',
  MINOR_WITHOUT_IDENTIFICATION = 'MENOR DE EDAD SIN IDENTIFICACIÓN',
  ADULT_WITHOUT_IDENTIFICATION = 'MAYOR DE EDAD SIN IDENTIFICACIÓN',
}
