export enum RequirementStatusEnum {
  CREATED = 'CREADA',
  VISUALIZED = 'VISUALIZADA',
  UNDER_REVIEW = 'EN REVISIÓN',
  DELIVERED = 'DOCS. ENTREGADOS',
  REJECTED = 'RECHAZADA',
  EXPIRED = 'DOCS. EXPIRADOS',
}
