"use strict";
var __esDecorate = (this && this.__esDecorate) || function (ctor, descriptorIn, decorators, contextIn, initializers, extraInitializers) {
    function accept(f) { if (f !== void 0 && typeof f !== "function") throw new TypeError("Function expected"); return f; }
    var kind = contextIn.kind, key = kind === "getter" ? "get" : kind === "setter" ? "set" : "value";
    var target = !descriptorIn && ctor ? contextIn["static"] ? ctor : ctor.prototype : null;
    var descriptor = descriptorIn || (target ? Object.getOwnPropertyDescriptor(target, contextIn.name) : {});
    var _, done = false;
    for (var i = decorators.length - 1; i >= 0; i--) {
        var context = {};
        for (var p in contextIn) context[p] = p === "access" ? {} : contextIn[p];
        for (var p in contextIn.access) context.access[p] = contextIn.access[p];
        context.addInitializer = function (f) { if (done) throw new TypeError("Cannot add initializers after decoration has completed"); extraInitializers.push(accept(f || null)); };
        var result = (0, decorators[i])(kind === "accessor" ? { get: descriptor.get, set: descriptor.set } : descriptor[key], context);
        if (kind === "accessor") {
            if (result === void 0) continue;
            if (result === null || typeof result !== "object") throw new TypeError("Object expected");
            if (_ = accept(result.get)) descriptor.get = _;
            if (_ = accept(result.set)) descriptor.set = _;
            if (_ = accept(result.init)) initializers.unshift(_);
        }
        else if (_ = accept(result)) {
            if (kind === "field") initializers.unshift(_);
            else descriptor[key] = _;
        }
    }
    if (target) Object.defineProperty(target, contextIn.name, descriptor);
    done = true;
};
var __runInitializers = (this && this.__runInitializers) || function (thisArg, initializers, value) {
    var useValue = arguments.length > 2;
    for (var i = 0; i < initializers.length; i++) {
        value = useValue ? initializers[i].call(thisArg, value) : initializers[i].call(thisArg);
    }
    return useValue ? value : void 0;
};
var __setFunctionName = (this && this.__setFunctionName) || function (f, name, prefix) {
    if (typeof name === "symbol") name = name.description ? "[".concat(name.description, "]") : "";
    return Object.defineProperty(f, "name", { configurable: true, value: prefix ? "".concat(prefix, " ", name) : name });
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.User = void 0;
var openapi = require("@nestjs/swagger");
var user_role_entity_1 = require("../../user_roles/entities/user_role.entity");
var gender_entity_1 = require("../../genders/entities/gender.entity");
var id_type_entity_1 = require("../../id_types/entities/id_type.entity");
var eps_company_entity_1 = require("../../eps_company/entities/eps_company.entity");
var company_area_entity_1 = require("../../company_area/entities/company_area.entity");
var medical_req_entity_1 = require("../../medical_req/entities/medical_req.entity");
var authorized_familiar_entity_1 = require("../../authorized_familiar/entities/authorized_familiar.entity");
var authentication_method_entity_1 = require("../../authentication_method/entities/authentication_method.entity");
var typeorm_1 = require("typeorm");
var User = function () {
    var _classDecorators = [(0, typeorm_1.Entity)()];
    var _classDescriptor;
    var _classExtraInitializers = [];
    var _classThis;
    var _id_decorators;
    var _id_initializers = [];
    var _id_extraInitializers = [];
    var _name_decorators;
    var _name_initializers = [];
    var _name_extraInitializers = [];
    var _last_name_decorators;
    var _last_name_initializers = [];
    var _last_name_extraInitializers = [];
    var _id_number_decorators;
    var _id_number_initializers = [];
    var _id_number_extraInitializers = [];
    var _birthdate_decorators;
    var _birthdate_initializers = [];
    var _birthdate_extraInitializers = [];
    var _email_decorators;
    var _email_initializers = [];
    var _email_extraInitializers = [];
    var _cellphone_decorators;
    var _cellphone_initializers = [];
    var _cellphone_extraInitializers = [];
    var _whatsapp_decorators;
    var _whatsapp_initializers = [];
    var _whatsapp_extraInitializers = [];
    var _password_decorators;
    var _password_initializers = [];
    var _password_extraInitializers = [];
    var _affiliation_eps_decorators;
    var _affiliation_eps_initializers = [];
    var _affiliation_eps_extraInitializers = [];
    var _residence_department_decorators;
    var _residence_department_initializers = [];
    var _residence_department_extraInitializers = [];
    var _residence_city_decorators;
    var _residence_city_initializers = [];
    var _residence_city_extraInitializers = [];
    var _residence_address_decorators;
    var _residence_address_initializers = [];
    var _residence_address_extraInitializers = [];
    var _residence_neighborhood_decorators;
    var _residence_neighborhood_initializers = [];
    var _residence_neighborhood_extraInitializers = [];
    var _is_active_decorators;
    var _is_active_initializers = [];
    var _is_active_extraInitializers = [];
    var _accept_terms_decorators;
    var _accept_terms_initializers = [];
    var _accept_terms_extraInitializers = [];
    var _createdAt_decorators;
    var _createdAt_initializers = [];
    var _createdAt_extraInitializers = [];
    var _updateAt_decorators;
    var _updateAt_initializers = [];
    var _updateAt_extraInitializers = [];
    var _deletedAt_decorators;
    var _deletedAt_initializers = [];
    var _deletedAt_extraInitializers = [];
    var _medical_req_decorators;
    var _medical_req_initializers = [];
    var _medical_req_extraInitializers = [];
    var _role_decorators;
    var _role_initializers = [];
    var _role_extraInitializers = [];
    var _user_role_decorators;
    var _user_role_initializers = [];
    var _user_role_extraInitializers = [];
    var _gender_decorators;
    var _gender_initializers = [];
    var _gender_extraInitializers = [];
    var _user_gender_decorators;
    var _user_gender_initializers = [];
    var _user_gender_extraInitializers = [];
    var _id_type_decorators;
    var _id_type_initializers = [];
    var _id_type_extraInitializers = [];
    var _user_id_type_decorators;
    var _user_id_type_initializers = [];
    var _user_id_type_extraInitializers = [];
    var _eps_decorators;
    var _eps_initializers = [];
    var _eps_extraInitializers = [];
    var _eps_company_decorators;
    var _eps_company_initializers = [];
    var _eps_company_extraInitializers = [];
    var _company_user_area_decorators;
    var _company_user_area_initializers = [];
    var _company_user_area_extraInitializers = [];
    var _company_area_decorators;
    var _company_area_initializers = [];
    var _company_area_extraInitializers = [];
    var _user_authentication_method_decorators;
    var _user_authentication_method_initializers = [];
    var _user_authentication_method_extraInitializers = [];
    var _authentication_method_decorators;
    var _authentication_method_initializers = [];
    var _authentication_method_extraInitializers = [];
    var _familiar_decorators;
    var _familiar_initializers = [];
    var _familiar_extraInitializers = [];
    var _verification_code_decorators;
    var _verification_code_initializers = [];
    var _verification_code_extraInitializers = [];
    var _reset_password_token_decorators;
    var _reset_password_token_initializers = [];
    var _reset_password_token_extraInitializers = [];
    var User = _classThis = /** @class */ (function () {
        function User_1() {
            this.id = __runInitializers(this, _id_initializers, void 0);
            this.name = (__runInitializers(this, _id_extraInitializers), __runInitializers(this, _name_initializers, void 0));
            this.last_name = (__runInitializers(this, _name_extraInitializers), __runInitializers(this, _last_name_initializers, void 0));
            this.id_number = (__runInitializers(this, _last_name_extraInitializers), __runInitializers(this, _id_number_initializers, void 0));
            this.birthdate = (__runInitializers(this, _id_number_extraInitializers), __runInitializers(this, _birthdate_initializers, void 0));
            this.email = (__runInitializers(this, _birthdate_extraInitializers), __runInitializers(this, _email_initializers, void 0));
            this.cellphone = (__runInitializers(this, _email_extraInitializers), __runInitializers(this, _cellphone_initializers, void 0));
            this.whatsapp = (__runInitializers(this, _cellphone_extraInitializers), __runInitializers(this, _whatsapp_initializers, void 0));
            this.password = (__runInitializers(this, _whatsapp_extraInitializers), __runInitializers(this, _password_initializers, void 0));
            this.affiliation_eps = (__runInitializers(this, _password_extraInitializers), __runInitializers(this, _affiliation_eps_initializers, void 0));
            this.residence_department = (__runInitializers(this, _affiliation_eps_extraInitializers), __runInitializers(this, _residence_department_initializers, void 0));
            this.residence_city = (__runInitializers(this, _residence_department_extraInitializers), __runInitializers(this, _residence_city_initializers, void 0));
            this.residence_address = (__runInitializers(this, _residence_city_extraInitializers), __runInitializers(this, _residence_address_initializers, void 0));
            this.residence_neighborhood = (__runInitializers(this, _residence_address_extraInitializers), __runInitializers(this, _residence_neighborhood_initializers, void 0));
            this.is_active = (__runInitializers(this, _residence_neighborhood_extraInitializers), __runInitializers(this, _is_active_initializers, void 0));
            this.accept_terms = (__runInitializers(this, _is_active_extraInitializers), __runInitializers(this, _accept_terms_initializers, void 0));
            this.createdAt = (__runInitializers(this, _accept_terms_extraInitializers), __runInitializers(this, _createdAt_initializers, void 0));
            this.updateAt = (__runInitializers(this, _createdAt_extraInitializers), __runInitializers(this, _updateAt_initializers, void 0));
            this.deletedAt = (__runInitializers(this, _updateAt_extraInitializers), __runInitializers(this, _deletedAt_initializers, void 0));
            this.medical_req = (__runInitializers(this, _deletedAt_extraInitializers), __runInitializers(this, _medical_req_initializers, void 0));
            this.role = (__runInitializers(this, _medical_req_extraInitializers), __runInitializers(this, _role_initializers, void 0));
            this.user_role = (__runInitializers(this, _role_extraInitializers), __runInitializers(this, _user_role_initializers, void 0));
            this.gender = (__runInitializers(this, _user_role_extraInitializers), __runInitializers(this, _gender_initializers, void 0));
            this.user_gender = (__runInitializers(this, _gender_extraInitializers), __runInitializers(this, _user_gender_initializers, void 0));
            this.id_type = (__runInitializers(this, _user_gender_extraInitializers), __runInitializers(this, _id_type_initializers, void 0));
            this.user_id_type = (__runInitializers(this, _id_type_extraInitializers), __runInitializers(this, _user_id_type_initializers, void 0));
            this.eps = (__runInitializers(this, _user_id_type_extraInitializers), __runInitializers(this, _eps_initializers, void 0));
            this.eps_company = (__runInitializers(this, _eps_extraInitializers), __runInitializers(this, _eps_company_initializers, void 0));
            this.company_user_area = (__runInitializers(this, _eps_company_extraInitializers), __runInitializers(this, _company_user_area_initializers, void 0));
            this.company_area = (__runInitializers(this, _company_user_area_extraInitializers), __runInitializers(this, _company_area_initializers, void 0));
            this.user_authentication_method = (__runInitializers(this, _company_area_extraInitializers), __runInitializers(this, _user_authentication_method_initializers, void 0));
            this.authentication_method = (__runInitializers(this, _user_authentication_method_extraInitializers), __runInitializers(this, _authentication_method_initializers, void 0));
            this.familiar = (__runInitializers(this, _authentication_method_extraInitializers), __runInitializers(this, _familiar_initializers, void 0));
            this.verification_code = (__runInitializers(this, _familiar_extraInitializers), __runInitializers(this, _verification_code_initializers, void 0));
            this.reset_password_token = (__runInitializers(this, _verification_code_extraInitializers), __runInitializers(this, _reset_password_token_initializers, void 0));
            __runInitializers(this, _reset_password_token_extraInitializers);
        }
        User_1._OPENAPI_METADATA_FACTORY = function () {
            return { id: { required: true, type: function () { return String; } }, name: { required: true, type: function () { return String; } }, last_name: { required: true, type: function () { return String; } }, id_number: { required: true, type: function () { return Number; } }, birthdate: { required: true, type: function () { return Date; } }, email: { required: true, type: function () { return String; } }, cellphone: { required: true, type: function () { return Number; } }, whatsapp: { required: true, type: function () { return Number; } }, password: { required: true, type: function () { return String; } }, affiliation_eps: { required: true, type: function () { return String; } }, residence_department: { required: true, type: function () { return String; } }, residence_city: { required: true, type: function () { return String; } }, residence_address: { required: true, type: function () { return String; } }, residence_neighborhood: { required: true, type: function () { return String; } }, is_active: { required: true, type: function () { return Boolean; } }, accept_terms: { required: true, type: function () { return Boolean; } }, createdAt: { required: true, type: function () { return Date; } }, updateAt: { required: true, type: function () { return Date; } }, deletedAt: { required: true, type: function () { return Date; } }, medical_req: { required: true, type: function () { return [require("../../medical_req/entities/medical_req.entity").MedicalReq]; } }, role: { required: true, type: function () { return require("../../user_roles/entities/user_role.entity").UserRole; } }, user_role: { required: true, type: function () { return Number; } }, gender: { required: true, type: function () { return require("../../genders/entities/gender.entity").GenderType; } }, user_gender: { required: true, type: function () { return Number; } }, id_type: { required: true, type: function () { return require("../../id_types/entities/id_type.entity").IdTypeEntity; } }, user_id_type: { required: true, type: function () { return Number; } }, eps: { required: true, type: function () { return require("../../eps_company/entities/eps_company.entity").EpsCompany; } }, eps_company: { required: true, type: function () { return Number; } }, company_user_area: { required: true, type: function () { return require("../../company_area/entities/company_area.entity").CompanyArea; } }, company_area: { required: true, type: function () { return Number; } }, user_authentication_method: { required: true, type: function () { return require("../../authentication_method/entities/authentication_method.entity").AuthenticationMethod; } }, authentication_method: { required: true, type: function () { return Number; } }, familiar: { required: true, type: function () { return [require("../../authorized_familiar/entities/authorized_familiar.entity").AuthorizedFamiliar]; } }, verification_code: { required: true, type: function () { return Number; } }, reset_password_token: { required: true, type: function () { return String; } } };
        };
        return User_1;
    }());
    __setFunctionName(_classThis, "User");
    (function () {
        var _metadata = typeof Symbol === "function" && Symbol.metadata ? Object.create(null) : void 0;
        _id_decorators = [(0, typeorm_1.PrimaryGeneratedColumn)('uuid')];
        _name_decorators = [(0, typeorm_1.Column)({ type: 'text', nullable: true })];
        _last_name_decorators = [(0, typeorm_1.Column)({ type: 'text', nullable: true })];
        _id_number_decorators = [(0, typeorm_1.Column)({ type: 'bigint', unique: true })];
        _birthdate_decorators = [(0, typeorm_1.Column)({ type: 'date', nullable: true })];
        _email_decorators = [(0, typeorm_1.Column)({ unique: true })];
        _cellphone_decorators = [(0, typeorm_1.Column)({ type: 'bigint', nullable: true })];
        _whatsapp_decorators = [(0, typeorm_1.Column)({ type: 'bigint', nullable: true })];
        _password_decorators = [(0, typeorm_1.Column)({ select: false })];
        _affiliation_eps_decorators = [(0, typeorm_1.Column)({ nullable: true })];
        _residence_department_decorators = [(0, typeorm_1.Column)({ nullable: true })];
        _residence_city_decorators = [(0, typeorm_1.Column)({ nullable: true })];
        _residence_address_decorators = [(0, typeorm_1.Column)({ nullable: true })];
        _residence_neighborhood_decorators = [(0, typeorm_1.Column)({ nullable: true })];
        _is_active_decorators = [(0, typeorm_1.Column)({ type: 'boolean', default: true })];
        _accept_terms_decorators = [(0, typeorm_1.Column)({ type: 'boolean', default: false })];
        _createdAt_decorators = [(0, typeorm_1.CreateDateColumn)()];
        _updateAt_decorators = [(0, typeorm_1.UpdateDateColumn)()];
        _deletedAt_decorators = [(0, typeorm_1.DeleteDateColumn)()];
        _medical_req_decorators = [(0, typeorm_1.OneToMany)(function () { return medical_req_entity_1.MedicalReq; }, function (medical_req) { return medical_req.aplicant; }, {
                eager: true,
                cascade: true,
            })];
        _role_decorators = [(0, typeorm_1.ManyToOne)(function () { return user_role_entity_1.UserRole; }, function (role) { return role.user; }, {
                eager: true,
                cascade: true,
            }), (0, typeorm_1.JoinColumn)({ name: 'user_role', referencedColumnName: 'id' })];
        _user_role_decorators = [(0, typeorm_1.Column)()];
        _gender_decorators = [(0, typeorm_1.ManyToOne)(function () { return gender_entity_1.GenderType; }, function (gender) { return gender.user; }), (0, typeorm_1.JoinColumn)({ name: 'user_gender', referencedColumnName: 'id' })];
        _user_gender_decorators = [(0, typeorm_1.Column)()];
        _id_type_decorators = [(0, typeorm_1.ManyToOne)(function () { return id_type_entity_1.IdTypeEntity; }, function (id_type) { return id_type.user; }), (0, typeorm_1.JoinColumn)({ name: 'user_id_type', referencedColumnName: 'id' })];
        _user_id_type_decorators = [(0, typeorm_1.Column)()];
        _eps_decorators = [(0, typeorm_1.ManyToOne)(function () { return eps_company_entity_1.EpsCompany; }, function (eps) { return eps.user; }), (0, typeorm_1.JoinColumn)({ name: 'eps_company', referencedColumnName: 'id' })];
        _eps_company_decorators = [(0, typeorm_1.Column)({ nullable: true })];
        _company_user_area_decorators = [(0, typeorm_1.ManyToOne)(function () { return company_area_entity_1.CompanyArea; }, function (company_user_area) { return company_user_area.user; }), (0, typeorm_1.JoinColumn)({ name: 'company_area', referencedColumnName: 'id' })];
        _company_area_decorators = [(0, typeorm_1.Column)({ nullable: true })];
        _user_authentication_method_decorators = [(0, typeorm_1.ManyToOne)(function () { return authentication_method_entity_1.AuthenticationMethod; }, function (user_authentication_method) { return user_authentication_method.user; }), (0, typeorm_1.JoinColumn)({ name: 'authentication_method', referencedColumnName: 'id' })];
        _authentication_method_decorators = [(0, typeorm_1.Column)({ nullable: true })];
        _familiar_decorators = [(0, typeorm_1.ManyToMany)(function () { return authorized_familiar_entity_1.AuthorizedFamiliar; }, {
                eager: true,
                cascade: true,
            }), (0, typeorm_1.JoinTable)({ name: 'patientUsers_authorizedRelatives' })];
        _verification_code_decorators = [(0, typeorm_1.Column)({ nullable: true })];
        _reset_password_token_decorators = [(0, typeorm_1.Column)({ nullable: true })];
        __esDecorate(null, null, _id_decorators, { kind: "field", name: "id", static: false, private: false, access: { has: function (obj) { return "id" in obj; }, get: function (obj) { return obj.id; }, set: function (obj, value) { obj.id = value; } }, metadata: _metadata }, _id_initializers, _id_extraInitializers);
        __esDecorate(null, null, _name_decorators, { kind: "field", name: "name", static: false, private: false, access: { has: function (obj) { return "name" in obj; }, get: function (obj) { return obj.name; }, set: function (obj, value) { obj.name = value; } }, metadata: _metadata }, _name_initializers, _name_extraInitializers);
        __esDecorate(null, null, _last_name_decorators, { kind: "field", name: "last_name", static: false, private: false, access: { has: function (obj) { return "last_name" in obj; }, get: function (obj) { return obj.last_name; }, set: function (obj, value) { obj.last_name = value; } }, metadata: _metadata }, _last_name_initializers, _last_name_extraInitializers);
        __esDecorate(null, null, _id_number_decorators, { kind: "field", name: "id_number", static: false, private: false, access: { has: function (obj) { return "id_number" in obj; }, get: function (obj) { return obj.id_number; }, set: function (obj, value) { obj.id_number = value; } }, metadata: _metadata }, _id_number_initializers, _id_number_extraInitializers);
        __esDecorate(null, null, _birthdate_decorators, { kind: "field", name: "birthdate", static: false, private: false, access: { has: function (obj) { return "birthdate" in obj; }, get: function (obj) { return obj.birthdate; }, set: function (obj, value) { obj.birthdate = value; } }, metadata: _metadata }, _birthdate_initializers, _birthdate_extraInitializers);
        __esDecorate(null, null, _email_decorators, { kind: "field", name: "email", static: false, private: false, access: { has: function (obj) { return "email" in obj; }, get: function (obj) { return obj.email; }, set: function (obj, value) { obj.email = value; } }, metadata: _metadata }, _email_initializers, _email_extraInitializers);
        __esDecorate(null, null, _cellphone_decorators, { kind: "field", name: "cellphone", static: false, private: false, access: { has: function (obj) { return "cellphone" in obj; }, get: function (obj) { return obj.cellphone; }, set: function (obj, value) { obj.cellphone = value; } }, metadata: _metadata }, _cellphone_initializers, _cellphone_extraInitializers);
        __esDecorate(null, null, _whatsapp_decorators, { kind: "field", name: "whatsapp", static: false, private: false, access: { has: function (obj) { return "whatsapp" in obj; }, get: function (obj) { return obj.whatsapp; }, set: function (obj, value) { obj.whatsapp = value; } }, metadata: _metadata }, _whatsapp_initializers, _whatsapp_extraInitializers);
        __esDecorate(null, null, _password_decorators, { kind: "field", name: "password", static: false, private: false, access: { has: function (obj) { return "password" in obj; }, get: function (obj) { return obj.password; }, set: function (obj, value) { obj.password = value; } }, metadata: _metadata }, _password_initializers, _password_extraInitializers);
        __esDecorate(null, null, _affiliation_eps_decorators, { kind: "field", name: "affiliation_eps", static: false, private: false, access: { has: function (obj) { return "affiliation_eps" in obj; }, get: function (obj) { return obj.affiliation_eps; }, set: function (obj, value) { obj.affiliation_eps = value; } }, metadata: _metadata }, _affiliation_eps_initializers, _affiliation_eps_extraInitializers);
        __esDecorate(null, null, _residence_department_decorators, { kind: "field", name: "residence_department", static: false, private: false, access: { has: function (obj) { return "residence_department" in obj; }, get: function (obj) { return obj.residence_department; }, set: function (obj, value) { obj.residence_department = value; } }, metadata: _metadata }, _residence_department_initializers, _residence_department_extraInitializers);
        __esDecorate(null, null, _residence_city_decorators, { kind: "field", name: "residence_city", static: false, private: false, access: { has: function (obj) { return "residence_city" in obj; }, get: function (obj) { return obj.residence_city; }, set: function (obj, value) { obj.residence_city = value; } }, metadata: _metadata }, _residence_city_initializers, _residence_city_extraInitializers);
        __esDecorate(null, null, _residence_address_decorators, { kind: "field", name: "residence_address", static: false, private: false, access: { has: function (obj) { return "residence_address" in obj; }, get: function (obj) { return obj.residence_address; }, set: function (obj, value) { obj.residence_address = value; } }, metadata: _metadata }, _residence_address_initializers, _residence_address_extraInitializers);
        __esDecorate(null, null, _residence_neighborhood_decorators, { kind: "field", name: "residence_neighborhood", static: false, private: false, access: { has: function (obj) { return "residence_neighborhood" in obj; }, get: function (obj) { return obj.residence_neighborhood; }, set: function (obj, value) { obj.residence_neighborhood = value; } }, metadata: _metadata }, _residence_neighborhood_initializers, _residence_neighborhood_extraInitializers);
        __esDecorate(null, null, _is_active_decorators, { kind: "field", name: "is_active", static: false, private: false, access: { has: function (obj) { return "is_active" in obj; }, get: function (obj) { return obj.is_active; }, set: function (obj, value) { obj.is_active = value; } }, metadata: _metadata }, _is_active_initializers, _is_active_extraInitializers);
        __esDecorate(null, null, _accept_terms_decorators, { kind: "field", name: "accept_terms", static: false, private: false, access: { has: function (obj) { return "accept_terms" in obj; }, get: function (obj) { return obj.accept_terms; }, set: function (obj, value) { obj.accept_terms = value; } }, metadata: _metadata }, _accept_terms_initializers, _accept_terms_extraInitializers);
        __esDecorate(null, null, _createdAt_decorators, { kind: "field", name: "createdAt", static: false, private: false, access: { has: function (obj) { return "createdAt" in obj; }, get: function (obj) { return obj.createdAt; }, set: function (obj, value) { obj.createdAt = value; } }, metadata: _metadata }, _createdAt_initializers, _createdAt_extraInitializers);
        __esDecorate(null, null, _updateAt_decorators, { kind: "field", name: "updateAt", static: false, private: false, access: { has: function (obj) { return "updateAt" in obj; }, get: function (obj) { return obj.updateAt; }, set: function (obj, value) { obj.updateAt = value; } }, metadata: _metadata }, _updateAt_initializers, _updateAt_extraInitializers);
        __esDecorate(null, null, _deletedAt_decorators, { kind: "field", name: "deletedAt", static: false, private: false, access: { has: function (obj) { return "deletedAt" in obj; }, get: function (obj) { return obj.deletedAt; }, set: function (obj, value) { obj.deletedAt = value; } }, metadata: _metadata }, _deletedAt_initializers, _deletedAt_extraInitializers);
        __esDecorate(null, null, _medical_req_decorators, { kind: "field", name: "medical_req", static: false, private: false, access: { has: function (obj) { return "medical_req" in obj; }, get: function (obj) { return obj.medical_req; }, set: function (obj, value) { obj.medical_req = value; } }, metadata: _metadata }, _medical_req_initializers, _medical_req_extraInitializers);
        __esDecorate(null, null, _role_decorators, { kind: "field", name: "role", static: false, private: false, access: { has: function (obj) { return "role" in obj; }, get: function (obj) { return obj.role; }, set: function (obj, value) { obj.role = value; } }, metadata: _metadata }, _role_initializers, _role_extraInitializers);
        __esDecorate(null, null, _user_role_decorators, { kind: "field", name: "user_role", static: false, private: false, access: { has: function (obj) { return "user_role" in obj; }, get: function (obj) { return obj.user_role; }, set: function (obj, value) { obj.user_role = value; } }, metadata: _metadata }, _user_role_initializers, _user_role_extraInitializers);
        __esDecorate(null, null, _gender_decorators, { kind: "field", name: "gender", static: false, private: false, access: { has: function (obj) { return "gender" in obj; }, get: function (obj) { return obj.gender; }, set: function (obj, value) { obj.gender = value; } }, metadata: _metadata }, _gender_initializers, _gender_extraInitializers);
        __esDecorate(null, null, _user_gender_decorators, { kind: "field", name: "user_gender", static: false, private: false, access: { has: function (obj) { return "user_gender" in obj; }, get: function (obj) { return obj.user_gender; }, set: function (obj, value) { obj.user_gender = value; } }, metadata: _metadata }, _user_gender_initializers, _user_gender_extraInitializers);
        __esDecorate(null, null, _id_type_decorators, { kind: "field", name: "id_type", static: false, private: false, access: { has: function (obj) { return "id_type" in obj; }, get: function (obj) { return obj.id_type; }, set: function (obj, value) { obj.id_type = value; } }, metadata: _metadata }, _id_type_initializers, _id_type_extraInitializers);
        __esDecorate(null, null, _user_id_type_decorators, { kind: "field", name: "user_id_type", static: false, private: false, access: { has: function (obj) { return "user_id_type" in obj; }, get: function (obj) { return obj.user_id_type; }, set: function (obj, value) { obj.user_id_type = value; } }, metadata: _metadata }, _user_id_type_initializers, _user_id_type_extraInitializers);
        __esDecorate(null, null, _eps_decorators, { kind: "field", name: "eps", static: false, private: false, access: { has: function (obj) { return "eps" in obj; }, get: function (obj) { return obj.eps; }, set: function (obj, value) { obj.eps = value; } }, metadata: _metadata }, _eps_initializers, _eps_extraInitializers);
        __esDecorate(null, null, _eps_company_decorators, { kind: "field", name: "eps_company", static: false, private: false, access: { has: function (obj) { return "eps_company" in obj; }, get: function (obj) { return obj.eps_company; }, set: function (obj, value) { obj.eps_company = value; } }, metadata: _metadata }, _eps_company_initializers, _eps_company_extraInitializers);
        __esDecorate(null, null, _company_user_area_decorators, { kind: "field", name: "company_user_area", static: false, private: false, access: { has: function (obj) { return "company_user_area" in obj; }, get: function (obj) { return obj.company_user_area; }, set: function (obj, value) { obj.company_user_area = value; } }, metadata: _metadata }, _company_user_area_initializers, _company_user_area_extraInitializers);
        __esDecorate(null, null, _company_area_decorators, { kind: "field", name: "company_area", static: false, private: false, access: { has: function (obj) { return "company_area" in obj; }, get: function (obj) { return obj.company_area; }, set: function (obj, value) { obj.company_area = value; } }, metadata: _metadata }, _company_area_initializers, _company_area_extraInitializers);
        __esDecorate(null, null, _user_authentication_method_decorators, { kind: "field", name: "user_authentication_method", static: false, private: false, access: { has: function (obj) { return "user_authentication_method" in obj; }, get: function (obj) { return obj.user_authentication_method; }, set: function (obj, value) { obj.user_authentication_method = value; } }, metadata: _metadata }, _user_authentication_method_initializers, _user_authentication_method_extraInitializers);
        __esDecorate(null, null, _authentication_method_decorators, { kind: "field", name: "authentication_method", static: false, private: false, access: { has: function (obj) { return "authentication_method" in obj; }, get: function (obj) { return obj.authentication_method; }, set: function (obj, value) { obj.authentication_method = value; } }, metadata: _metadata }, _authentication_method_initializers, _authentication_method_extraInitializers);
        __esDecorate(null, null, _familiar_decorators, { kind: "field", name: "familiar", static: false, private: false, access: { has: function (obj) { return "familiar" in obj; }, get: function (obj) { return obj.familiar; }, set: function (obj, value) { obj.familiar = value; } }, metadata: _metadata }, _familiar_initializers, _familiar_extraInitializers);
        __esDecorate(null, null, _verification_code_decorators, { kind: "field", name: "verification_code", static: false, private: false, access: { has: function (obj) { return "verification_code" in obj; }, get: function (obj) { return obj.verification_code; }, set: function (obj, value) { obj.verification_code = value; } }, metadata: _metadata }, _verification_code_initializers, _verification_code_extraInitializers);
        __esDecorate(null, null, _reset_password_token_decorators, { kind: "field", name: "reset_password_token", static: false, private: false, access: { has: function (obj) { return "reset_password_token" in obj; }, get: function (obj) { return obj.reset_password_token; }, set: function (obj, value) { obj.reset_password_token = value; } }, metadata: _metadata }, _reset_password_token_initializers, _reset_password_token_extraInitializers);
        __esDecorate(null, _classDescriptor = { value: _classThis }, _classDecorators, { kind: "class", name: _classThis.name, metadata: _metadata }, null, _classExtraInitializers);
        User = _classThis = _classDescriptor.value;
        if (_metadata) Object.defineProperty(_classThis, Symbol.metadata, { enumerable: true, configurable: true, writable: true, value: _metadata });
        __runInitializers(_classThis, _classExtraInitializers);
    })();
    return User = _classThis;
}();
exports.User = User;
