export enum RequirementStatusEnum {
  CREATED = 'SOLICITUD CREADA',
  VISUALIZED = 'VISUALIZADO',
  UNDER_REVIEW = 'EN REVISIÓN',
  DELIVERED = 'ENTREGADA',
  REJECTED = 'RECHAZADA',
  EXPIRED = 'EXPIRADA',
}
