services:
  portal-web-frontend:
    image: portal-web-frontend:1.0.0
    container_name: portal-web-frontend
    ports:
      - "4000:4000"
    restart: always
    env_file: ../../environments/portal_web.env
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/ssl:/etc/nginx/ssl:ro
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: always
