export enum CompanyAreaEnum {
  EXTERNAL_AUDITOR = 'AUDITOR EXTERNO',
  SYSTEM_DEPARTAMENT = 'DEPARTAMENTO DE SISTEMAS',
  ARCHIVES_DEPARTAMENT = 'DEPARTAMENTO DE ARCHIVOS',
  LEGAL_DEPARTAMENT = 'DEPARTAMENTO JURÍDICO',
  ADMISSIONS_DEPARTMENT = 'DEPARTAMENTO DE ADMISIONES',
  COMMERCIAL = 'DEPARTAMENTO COMERCIAL',
  HUMAN_RESOURCES = 'DEPARTAMENTO DE RECURSOS HUMANOS',
  ACCOUNTING_FINANCE = 'DEPARTAMENTO DE CONTABILIDAD Y FINANZAS',
  MARKETING = 'DEPARTAMENTO DE MARKETING',
  PURCHASING_DEPARTMENT = 'DEPARTAMENTO DE COMPRAS',
  MAINTENANCE_DEPARTMENT = 'DEPARTAMENTO DE MANTENIMIENTO',
  CARE_AREA = 'ÁREA ASISTENCIAL',
}
