"use strict";
var __esDecorate = (this && this.__esDecorate) || function (ctor, descriptorIn, decorators, contextIn, initializers, extraInitializers) {
    function accept(f) { if (f !== void 0 && typeof f !== "function") throw new TypeError("Function expected"); return f; }
    var kind = contextIn.kind, key = kind === "getter" ? "get" : kind === "setter" ? "set" : "value";
    var target = !descriptorIn && ctor ? contextIn["static"] ? ctor : ctor.prototype : null;
    var descriptor = descriptorIn || (target ? Object.getOwnPropertyDescriptor(target, contextIn.name) : {});
    var _, done = false;
    for (var i = decorators.length - 1; i >= 0; i--) {
        var context = {};
        for (var p in contextIn) context[p] = p === "access" ? {} : contextIn[p];
        for (var p in contextIn.access) context.access[p] = contextIn.access[p];
        context.addInitializer = function (f) { if (done) throw new TypeError("Cannot add initializers after decoration has completed"); extraInitializers.push(accept(f || null)); };
        var result = (0, decorators[i])(kind === "accessor" ? { get: descriptor.get, set: descriptor.set } : descriptor[key], context);
        if (kind === "accessor") {
            if (result === void 0) continue;
            if (result === null || typeof result !== "object") throw new TypeError("Object expected");
            if (_ = accept(result.get)) descriptor.get = _;
            if (_ = accept(result.set)) descriptor.set = _;
            if (_ = accept(result.init)) initializers.unshift(_);
        }
        else if (_ = accept(result)) {
            if (kind === "field") initializers.unshift(_);
            else descriptor[key] = _;
        }
    }
    if (target) Object.defineProperty(target, contextIn.name, descriptor);
    done = true;
};
var __runInitializers = (this && this.__runInitializers) || function (thisArg, initializers, value) {
    var useValue = arguments.length > 2;
    for (var i = 0; i < initializers.length; i++) {
        value = useValue ? initializers[i].call(thisArg, value) : initializers[i].call(thisArg);
    }
    return useValue ? value : void 0;
};
var __setFunctionName = (this && this.__setFunctionName) || function (f, name, prefix) {
    if (typeof name === "symbol") name = name.description ? "[".concat(name.description, "]") : "";
    return Object.defineProperty(f, "name", { configurable: true, value: prefix ? "".concat(prefix, " ", name) : name });
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.MedicalReq = void 0;
var openapi = require("@nestjs/swagger");
var user_entity_1 = require("../../users/entities/user.entity");
var requirement_type_entity_1 = require("../../requirement_type/entities/requirement_type.entity");
var requirement_status_entity_1 = require("../../requirement_status/entities/requirement_status.entity");
var patient_class_status_entity_1 = require("../../patient_class_status/entities/patient_class_status.entity");
var company_area_entity_1 = require("../../company_area/entities/company_area.entity");
var authorized_familiar_entity_1 = require("../../authorized_familiar/entities/authorized_familiar.entity");
var reasons_for_rejection_entity_1 = require("../../reasons_for_rejection/entities/reasons_for_rejection.entity");
var typeorm_1 = require("typeorm");
var MedicalReq = function () {
    var _classDecorators = [(0, typeorm_1.Entity)()];
    var _classDescriptor;
    var _classExtraInitializers = [];
    var _classThis;
    var _id_decorators;
    var _id_initializers = [];
    var _id_extraInitializers = [];
    var _filing_number_decorators;
    var _filing_number_initializers = [];
    var _filing_number_extraInitializers = [];
    var _req_type_decorators;
    var _req_type_initializers = [];
    var _req_type_extraInitializers = [];
    var _requirement_type_decorators;
    var _requirement_type_initializers = [];
    var _requirement_type_extraInitializers = [];
    var _registration_dates_decorators;
    var _registration_dates_initializers = [];
    var _registration_dates_extraInitializers = [];
    var _right_petition_decorators;
    var _right_petition_initializers = [];
    var _right_petition_extraInitializers = [];
    var _copy_right_petition_decorators;
    var _copy_right_petition_initializers = [];
    var _copy_right_petition_extraInitializers = [];
    var _medicalReqUserType_decorators;
    var _medicalReqUserType_initializers = [];
    var _medicalReqUserType_extraInitializers = [];
    var _familiar_decorators;
    var _familiar_initializers = [];
    var _familiar_extraInitializers = [];
    var _familiar_id_decorators;
    var _familiar_id_initializers = [];
    var _familiar_id_extraInitializers = [];
    var _aplicantId_decorators;
    var _aplicantId_initializers = [];
    var _aplicantId_extraInitializers = [];
    var _patient_class_decorators;
    var _patient_class_initializers = [];
    var _patient_class_extraInitializers = [];
    var _patient_class_status_decorators;
    var _patient_class_status_initializers = [];
    var _patient_class_status_extraInitializers = [];
    var _relationship_with_patient_decorators;
    var _relationship_with_patient_initializers = [];
    var _relationship_with_patient_extraInitializers = [];
    var _patient_name_decorators;
    var _patient_name_initializers = [];
    var _patient_name_extraInitializers = [];
    var _patient_id_type_decorators;
    var _patient_id_type_initializers = [];
    var _patient_id_type_extraInitializers = [];
    var _patient_id_number_decorators;
    var _patient_id_number_initializers = [];
    var _patient_id_number_extraInitializers = [];
    var _aplicant_name_decorators;
    var _aplicant_name_initializers = [];
    var _aplicant_name_extraInitializers = [];
    var _aplicant_last_name_decorators;
    var _aplicant_last_name_initializers = [];
    var _aplicant_last_name_extraInitializers = [];
    var _aplicant_gender_decorators;
    var _aplicant_gender_initializers = [];
    var _aplicant_gender_extraInitializers = [];
    var _aplicant_id_type_decorators;
    var _aplicant_id_type_initializers = [];
    var _aplicant_id_type_extraInitializers = [];
    var _aplicant_id_number_decorators;
    var _aplicant_id_number_initializers = [];
    var _aplicant_id_number_extraInitializers = [];
    var _aplicant_email_decorators;
    var _aplicant_email_initializers = [];
    var _aplicant_email_extraInitializers = [];
    var _aplicant_cellphone_decorators;
    var _aplicant_cellphone_initializers = [];
    var _aplicant_cellphone_extraInitializers = [];
    var _aplicant_eps_company_decorators;
    var _aplicant_eps_company_initializers = [];
    var _aplicant_eps_company_extraInitializers = [];
    var _aplicant_company_area_decorators;
    var _aplicant_company_area_initializers = [];
    var _aplicant_company_area_extraInitializers = [];
    var _accept_terms_decorators;
    var _accept_terms_initializers = [];
    var _accept_terms_extraInitializers = [];
    var _copy_applicant_identification_document_decorators;
    var _copy_applicant_identification_document_initializers = [];
    var _copy_applicant_identification_document_extraInitializers = [];
    var _copy_patient_citizenship_card_decorators;
    var _copy_patient_citizenship_card_initializers = [];
    var _copy_patient_citizenship_card_extraInitializers = [];
    var _copy_patient_civil_registration_decorators;
    var _copy_patient_civil_registration_initializers = [];
    var _copy_patient_civil_registration_extraInitializers = [];
    var _copy_parents_citizenship_card_decorators;
    var _copy_parents_citizenship_card_initializers = [];
    var _copy_parents_citizenship_card_extraInitializers = [];
    var _copy_marriage_certificate_decorators;
    var _copy_marriage_certificate_initializers = [];
    var _copy_marriage_certificate_extraInitializers = [];
    var _copy_cohabitation_certificate_decorators;
    var _copy_cohabitation_certificate_initializers = [];
    var _copy_cohabitation_certificate_extraInitializers = [];
    var _date_of_admission_decorators;
    var _date_of_admission_initializers = [];
    var _date_of_admission_extraInitializers = [];
    var _answer_date_decorators;
    var _answer_date_initializers = [];
    var _answer_date_extraInitializers = [];
    var _response_time_decorators;
    var _response_time_initializers = [];
    var _response_time_extraInitializers = [];
    var _download_expiration_date_decorators;
    var _download_expiration_date_initializers = [];
    var _download_expiration_date_extraInitializers = [];
    var _is_deleted_decorators;
    var _is_deleted_initializers = [];
    var _is_deleted_extraInitializers = [];
    var _createdAt_decorators;
    var _createdAt_initializers = [];
    var _createdAt_extraInitializers = [];
    var _updateAt_decorators;
    var _updateAt_initializers = [];
    var _updateAt_extraInitializers = [];
    var _deletedAt_decorators;
    var _deletedAt_initializers = [];
    var _deletedAt_extraInitializers = [];
    var _is_it_reviewed_decorators;
    var _is_it_reviewed_initializers = [];
    var _is_it_reviewed_extraInitializers = [];
    var _aplicant_decorators;
    var _aplicant_initializers = [];
    var _aplicant_extraInitializers = [];
    var _review_area_decorators;
    var _review_area_initializers = [];
    var _review_area_extraInitializers = [];
    var _currently_in_area_decorators;
    var _currently_in_area_initializers = [];
    var _currently_in_area_extraInitializers = [];
    var _area_redirection_message_decorators;
    var _area_redirection_message_initializers = [];
    var _area_redirection_message_extraInitializers = [];
    var _req_status_decorators;
    var _req_status_initializers = [];
    var _req_status_extraInitializers = [];
    var _requirement_status_decorators;
    var _requirement_status_initializers = [];
    var _requirement_status_extraInitializers = [];
    var _user_message_decorators;
    var _user_message_initializers = [];
    var _user_message_extraInitializers = [];
    var _user_message_documents_decorators;
    var _user_message_documents_initializers = [];
    var _user_message_documents_extraInitializers = [];
    var _response_comments_decorators;
    var _response_comments_initializers = [];
    var _response_comments_extraInitializers = [];
    var _reasons_for_rejection_decorators;
    var _reasons_for_rejection_initializers = [];
    var _reasons_for_rejection_extraInitializers = [];
    var _motive_for_rejection_decorators;
    var _motive_for_rejection_initializers = [];
    var _motive_for_rejection_extraInitializers = [];
    var _documents_delivered_decorators;
    var _documents_delivered_initializers = [];
    var _documents_delivered_extraInitializers = [];
    var _delegate_id_decorators;
    var _delegate_id_initializers = [];
    var _delegate_id_extraInitializers = [];
    var MedicalReq = _classThis = /** @class */ (function () {
        function MedicalReq_1() {
            this.id = __runInitializers(this, _id_initializers, void 0);
            this.filing_number = (__runInitializers(this, _id_extraInitializers), __runInitializers(this, _filing_number_initializers, void 0));
            this.req_type = (__runInitializers(this, _filing_number_extraInitializers), __runInitializers(this, _req_type_initializers, void 0));
            this.requirement_type = (__runInitializers(this, _req_type_extraInitializers), __runInitializers(this, _requirement_type_initializers, void 0));
            this.registration_dates = (__runInitializers(this, _requirement_type_extraInitializers), __runInitializers(this, _registration_dates_initializers, void 0));
            this.right_petition = (__runInitializers(this, _registration_dates_extraInitializers), __runInitializers(this, _right_petition_initializers, void 0));
            this.copy_right_petition = (__runInitializers(this, _right_petition_extraInitializers), __runInitializers(this, _copy_right_petition_initializers, void 0));
            this.medicalReqUserType = (__runInitializers(this, _copy_right_petition_extraInitializers), __runInitializers(this, _medicalReqUserType_initializers, void 0));
            this.familiar = (__runInitializers(this, _medicalReqUserType_extraInitializers), __runInitializers(this, _familiar_initializers, void 0));
            this.familiar_id = (__runInitializers(this, _familiar_extraInitializers), __runInitializers(this, _familiar_id_initializers, void 0));
            this.aplicantId = (__runInitializers(this, _familiar_id_extraInitializers), __runInitializers(this, _aplicantId_initializers, void 0));
            this.patient_class = (__runInitializers(this, _aplicantId_extraInitializers), __runInitializers(this, _patient_class_initializers, void 0));
            this.patient_class_status = (__runInitializers(this, _patient_class_extraInitializers), __runInitializers(this, _patient_class_status_initializers, void 0));
            this.relationship_with_patient = (__runInitializers(this, _patient_class_status_extraInitializers), __runInitializers(this, _relationship_with_patient_initializers, void 0));
            this.patient_name = (__runInitializers(this, _relationship_with_patient_extraInitializers), __runInitializers(this, _patient_name_initializers, void 0));
            this.patient_id_type = (__runInitializers(this, _patient_name_extraInitializers), __runInitializers(this, _patient_id_type_initializers, void 0));
            this.patient_id_number = (__runInitializers(this, _patient_id_type_extraInitializers), __runInitializers(this, _patient_id_number_initializers, void 0));
            this.aplicant_name = (__runInitializers(this, _patient_id_number_extraInitializers), __runInitializers(this, _aplicant_name_initializers, void 0));
            this.aplicant_last_name = (__runInitializers(this, _aplicant_name_extraInitializers), __runInitializers(this, _aplicant_last_name_initializers, void 0));
            this.aplicant_gender = (__runInitializers(this, _aplicant_last_name_extraInitializers), __runInitializers(this, _aplicant_gender_initializers, void 0));
            this.aplicant_id_type = (__runInitializers(this, _aplicant_gender_extraInitializers), __runInitializers(this, _aplicant_id_type_initializers, void 0));
            this.aplicant_id_number = (__runInitializers(this, _aplicant_id_type_extraInitializers), __runInitializers(this, _aplicant_id_number_initializers, void 0));
            this.aplicant_email = (__runInitializers(this, _aplicant_id_number_extraInitializers), __runInitializers(this, _aplicant_email_initializers, void 0));
            this.aplicant_cellphone = (__runInitializers(this, _aplicant_email_extraInitializers), __runInitializers(this, _aplicant_cellphone_initializers, void 0));
            this.aplicant_eps_company = (__runInitializers(this, _aplicant_cellphone_extraInitializers), __runInitializers(this, _aplicant_eps_company_initializers, void 0));
            this.aplicant_company_area = (__runInitializers(this, _aplicant_eps_company_extraInitializers), __runInitializers(this, _aplicant_company_area_initializers, void 0));
            this.accept_terms = (__runInitializers(this, _aplicant_company_area_extraInitializers), __runInitializers(this, _accept_terms_initializers, void 0));
            this.copy_applicant_identification_document = (__runInitializers(this, _accept_terms_extraInitializers), __runInitializers(this, _copy_applicant_identification_document_initializers, void 0));
            this.copy_patient_citizenship_card = (__runInitializers(this, _copy_applicant_identification_document_extraInitializers), __runInitializers(this, _copy_patient_citizenship_card_initializers, void 0));
            this.copy_patient_civil_registration = (__runInitializers(this, _copy_patient_citizenship_card_extraInitializers), __runInitializers(this, _copy_patient_civil_registration_initializers, void 0));
            this.copy_parents_citizenship_card = (__runInitializers(this, _copy_patient_civil_registration_extraInitializers), __runInitializers(this, _copy_parents_citizenship_card_initializers, void 0));
            this.copy_marriage_certificate = (__runInitializers(this, _copy_parents_citizenship_card_extraInitializers), __runInitializers(this, _copy_marriage_certificate_initializers, void 0));
            this.copy_cohabitation_certificate = (__runInitializers(this, _copy_marriage_certificate_extraInitializers), __runInitializers(this, _copy_cohabitation_certificate_initializers, void 0));
            this.date_of_admission = (__runInitializers(this, _copy_cohabitation_certificate_extraInitializers), __runInitializers(this, _date_of_admission_initializers, void 0));
            this.answer_date = (__runInitializers(this, _date_of_admission_extraInitializers), __runInitializers(this, _answer_date_initializers, void 0));
            this.response_time = (__runInitializers(this, _answer_date_extraInitializers), __runInitializers(this, _response_time_initializers, void 0));
            this.download_expiration_date = (__runInitializers(this, _response_time_extraInitializers), __runInitializers(this, _download_expiration_date_initializers, void 0));
            this.is_deleted = (__runInitializers(this, _download_expiration_date_extraInitializers), __runInitializers(this, _is_deleted_initializers, void 0));
            this.createdAt = (__runInitializers(this, _is_deleted_extraInitializers), __runInitializers(this, _createdAt_initializers, void 0));
            this.updateAt = (__runInitializers(this, _createdAt_extraInitializers), __runInitializers(this, _updateAt_initializers, void 0));
            this.deletedAt = (__runInitializers(this, _updateAt_extraInitializers), __runInitializers(this, _deletedAt_initializers, void 0));
            this.is_it_reviewed = (__runInitializers(this, _deletedAt_extraInitializers), __runInitializers(this, _is_it_reviewed_initializers, void 0));
            this.aplicant = (__runInitializers(this, _is_it_reviewed_extraInitializers), __runInitializers(this, _aplicant_initializers, void 0));
            this.review_area = (__runInitializers(this, _aplicant_extraInitializers), __runInitializers(this, _review_area_initializers, void 0));
            this.currently_in_area = (__runInitializers(this, _review_area_extraInitializers), __runInitializers(this, _currently_in_area_initializers, void 0));
            this.area_redirection_message = (__runInitializers(this, _currently_in_area_extraInitializers), __runInitializers(this, _area_redirection_message_initializers, void 0));
            this.req_status = (__runInitializers(this, _area_redirection_message_extraInitializers), __runInitializers(this, _req_status_initializers, void 0));
            this.requirement_status = (__runInitializers(this, _req_status_extraInitializers), __runInitializers(this, _requirement_status_initializers, void 0));
            this.user_message = (__runInitializers(this, _requirement_status_extraInitializers), __runInitializers(this, _user_message_initializers, void 0));
            this.user_message_documents = (__runInitializers(this, _user_message_extraInitializers), __runInitializers(this, _user_message_documents_initializers, void 0));
            this.response_comments = (__runInitializers(this, _user_message_documents_extraInitializers), __runInitializers(this, _response_comments_initializers, void 0));
            this.reasons_for_rejection = (__runInitializers(this, _response_comments_extraInitializers), __runInitializers(this, _reasons_for_rejection_initializers, void 0));
            this.motive_for_rejection = (__runInitializers(this, _reasons_for_rejection_extraInitializers), __runInitializers(this, _motive_for_rejection_initializers, void 0));
            this.documents_delivered = (__runInitializers(this, _motive_for_rejection_extraInitializers), __runInitializers(this, _documents_delivered_initializers, void 0));
            this.delegate_id = (__runInitializers(this, _documents_delivered_extraInitializers), __runInitializers(this, _delegate_id_initializers, void 0));
            __runInitializers(this, _delegate_id_extraInitializers);
        }
        MedicalReq_1._OPENAPI_METADATA_FACTORY = function () {
            return { id: { required: true, type: function () { return String; } }, filing_number: { required: true, type: function () { return String; } }, req_type: { required: true, type: function () { return require("../../requirement_type/entities/requirement_type.entity").RequirementType; } }, requirement_type: { required: true, type: function () { return Number; } }, registration_dates: { required: true, type: function () { return String; } }, right_petition: { required: true, type: function () { return Boolean; } }, copy_right_petition: { required: true, type: function () { return [String]; } }, medicalReqUserType: { required: true, type: function () { return Number; } }, familiar: { required: true, type: function () { return require("../../authorized_familiar/entities/authorized_familiar.entity").AuthorizedFamiliar; } }, familiar_id: { required: true, type: function () { return String; } }, aplicantId: { required: true, type: function () { return String; } }, patient_class: { required: true, type: function () { return require("../../patient_class_status/entities/patient_class_status.entity").PatientClassStatus; } }, patient_class_status: { required: true, type: function () { return Number; } }, relationship_with_patient: { required: true, type: function () { return Number; } }, patient_name: { required: true, type: function () { return String; } }, patient_id_type: { required: true, type: function () { return Number; } }, patient_id_number: { required: true, type: function () { return Number; } }, aplicant_name: { required: true, type: function () { return String; } }, aplicant_last_name: { required: true, type: function () { return String; } }, aplicant_gender: { required: true, type: function () { return Number; } }, aplicant_id_type: { required: true, type: function () { return Number; } }, aplicant_id_number: { required: true, type: function () { return Number; } }, aplicant_email: { required: true, type: function () { return String; } }, aplicant_cellphone: { required: true, type: function () { return Number; } }, aplicant_eps_company: { required: true, type: function () { return Number; } }, aplicant_company_area: { required: true, type: function () { return Number; } }, accept_terms: { required: true, type: function () { return Boolean; } }, copy_applicant_identification_document: { required: true, type: function () { return [String]; } }, copy_patient_citizenship_card: { required: true, type: function () { return [String]; } }, copy_patient_civil_registration: { required: true, type: function () { return [String]; } }, copy_parents_citizenship_card: { required: true, type: function () { return [String]; } }, copy_marriage_certificate: { required: true, type: function () { return [String]; } }, copy_cohabitation_certificate: { required: true, type: function () { return [String]; } }, date_of_admission: { required: true, type: function () { return Date; } }, answer_date: { required: true, type: function () { return Date; } }, response_time: { required: true, type: function () { return String; } }, download_expiration_date: { required: true, type: function () { return Date; } }, is_deleted: { required: true, type: function () { return Boolean; } }, createdAt: { required: true, type: function () { return Date; } }, updateAt: { required: true, type: function () { return Date; } }, deletedAt: { required: true, type: function () { return Date; } }, is_it_reviewed: { required: true, type: function () { return Boolean; } }, aplicant: { required: true, type: function () { return require("../../users/entities/user.entity").User; } }, review_area: { required: true, type: function () { return require("../../company_area/entities/company_area.entity").CompanyArea; } }, currently_in_area: { required: true, type: function () { return Number; } }, area_redirection_message: { required: true, type: function () { return String; } }, req_status: { required: true, type: function () { return require("../../requirement_status/entities/requirement_status.entity").RequirementStatus; } }, requirement_status: { required: true, type: function () { return Number; } }, user_message: { required: true, type: function () { return String; } }, user_message_documents: { required: true, type: function () { return [String]; } }, response_comments: { required: true, type: function () { return String; } }, reasons_for_rejection: { required: true, type: function () { return [require("../../reasons_for_rejection/entities/reasons_for_rejection.entity").ReasonsForRejection]; } }, motive_for_rejection: { required: true, type: function () { return [Number]; } }, documents_delivered: { required: true, type: function () { return [String]; } }, delegate_id: { required: true, type: function () { return String; } } };
        };
        return MedicalReq_1;
    }());
    __setFunctionName(_classThis, "MedicalReq");
    (function () {
        var _metadata = typeof Symbol === "function" && Symbol.metadata ? Object.create(null) : void 0;
        _id_decorators = [(0, typeorm_1.PrimaryGeneratedColumn)('uuid')];
        _filing_number_decorators = [(0, typeorm_1.Column)({ type: 'text' })];
        _req_type_decorators = [(0, typeorm_1.ManyToOne)(function () { return requirement_type_entity_1.RequirementType; }, function (req_type) { return req_type.medical_req; }), (0, typeorm_1.JoinColumn)({ name: 'requirement_type', referencedColumnName: 'id' })];
        _requirement_type_decorators = [(0, typeorm_1.Column)()];
        _registration_dates_decorators = [(0, typeorm_1.Column)({ type: 'text', nullable: false })];
        _right_petition_decorators = [(0, typeorm_1.Column)({ type: 'boolean', default: false })];
        _copy_right_petition_decorators = [(0, typeorm_1.Column)({ type: 'text', array: true, nullable: true })];
        _medicalReqUserType_decorators = [(0, typeorm_1.Column)({ nullable: true })];
        _familiar_decorators = [(0, typeorm_1.ManyToOne)(function () { return authorized_familiar_entity_1.AuthorizedFamiliar; }, function (familiar) { return familiar.medical_req; }), (0, typeorm_1.JoinColumn)({ name: 'familiar_id', referencedColumnName: 'id' })];
        _familiar_id_decorators = [(0, typeorm_1.Column)({ type: 'uuid', nullable: true })];
        _aplicantId_decorators = [(0, typeorm_1.Column)({ type: 'uuid', nullable: true })];
        _patient_class_decorators = [(0, typeorm_1.ManyToOne)(function () { return patient_class_status_entity_1.PatientClassStatus; }, function (patient_class) { return patient_class.medical_req; }), (0, typeorm_1.JoinColumn)({ name: 'patient_class_status', referencedColumnName: 'id' })];
        _patient_class_status_decorators = [(0, typeorm_1.Column)({ nullable: true })];
        _relationship_with_patient_decorators = [(0, typeorm_1.Column)({ nullable: true })];
        _patient_name_decorators = [(0, typeorm_1.Column)({ type: 'text', nullable: true })];
        _patient_id_type_decorators = [(0, typeorm_1.Column)()];
        _patient_id_number_decorators = [(0, typeorm_1.Column)({ type: 'bigint' })];
        _aplicant_name_decorators = [(0, typeorm_1.Column)({ type: 'text', nullable: true })];
        _aplicant_last_name_decorators = [(0, typeorm_1.Column)({ type: 'text', nullable: true })];
        _aplicant_gender_decorators = [(0, typeorm_1.Column)({ nullable: true })];
        _aplicant_id_type_decorators = [(0, typeorm_1.Column)({ nullable: true })];
        _aplicant_id_number_decorators = [(0, typeorm_1.Column)({ type: 'bigint', nullable: true })];
        _aplicant_email_decorators = [(0, typeorm_1.Column)({ nullable: true })];
        _aplicant_cellphone_decorators = [(0, typeorm_1.Column)({ type: 'bigint', nullable: true })];
        _aplicant_eps_company_decorators = [(0, typeorm_1.Column)({ nullable: true })];
        _aplicant_company_area_decorators = [(0, typeorm_1.Column)({ nullable: true })];
        _accept_terms_decorators = [(0, typeorm_1.Column)({ type: 'boolean', default: false })];
        _copy_applicant_identification_document_decorators = [(0, typeorm_1.Column)({ type: 'text', array: true, nullable: true })];
        _copy_patient_citizenship_card_decorators = [(0, typeorm_1.Column)({ type: 'text', array: true, nullable: true })];
        _copy_patient_civil_registration_decorators = [(0, typeorm_1.Column)({ type: 'text', array: true, nullable: true })];
        _copy_parents_citizenship_card_decorators = [(0, typeorm_1.Column)({ type: 'text', array: true, nullable: true })];
        _copy_marriage_certificate_decorators = [(0, typeorm_1.Column)({ type: 'text', array: true, nullable: true })];
        _copy_cohabitation_certificate_decorators = [(0, typeorm_1.Column)({ type: 'text', array: true, nullable: true })];
        _date_of_admission_decorators = [(0, typeorm_1.Column)({ type: 'date', nullable: true })];
        _answer_date_decorators = [(0, typeorm_1.Column)({ type: 'date', nullable: true })];
        _response_time_decorators = [(0, typeorm_1.Column)({ type: 'text', nullable: true })];
        _download_expiration_date_decorators = [(0, typeorm_1.Column)({ type: 'date', nullable: true })];
        _is_deleted_decorators = [(0, typeorm_1.Column)({ type: 'boolean', default: false })];
        _createdAt_decorators = [(0, typeorm_1.CreateDateColumn)()];
        _updateAt_decorators = [(0, typeorm_1.UpdateDateColumn)()];
        _deletedAt_decorators = [(0, typeorm_1.DeleteDateColumn)()];
        _is_it_reviewed_decorators = [(0, typeorm_1.Column)({ type: 'boolean', default: false })];
        _aplicant_decorators = [(0, typeorm_1.ManyToOne)(function () { return user_entity_1.User; }, function (aplicant) { return aplicant.medical_req; })];
        _review_area_decorators = [(0, typeorm_1.ManyToOne)(function () { return company_area_entity_1.CompanyArea; }, function (company_user_area) { return company_user_area.medical_req; }), (0, typeorm_1.JoinColumn)({ name: 'currently_in_area', referencedColumnName: 'id' })];
        _currently_in_area_decorators = [(0, typeorm_1.Column)({ nullable: true })];
        _area_redirection_message_decorators = [(0, typeorm_1.Column)({ type: 'text', nullable: true })];
        _req_status_decorators = [(0, typeorm_1.ManyToOne)(function () { return requirement_status_entity_1.RequirementStatus; }, function (req_status) { return req_status.medical_req; }), (0, typeorm_1.JoinColumn)({ name: 'requirement_status', referencedColumnName: 'id' })];
        _requirement_status_decorators = [(0, typeorm_1.Column)({ nullable: true })];
        _user_message_decorators = [(0, typeorm_1.Column)({ type: 'text', nullable: true })];
        _user_message_documents_decorators = [(0, typeorm_1.Column)({ type: 'text', array: true, nullable: true })];
        _response_comments_decorators = [(0, typeorm_1.Column)({ type: 'text', nullable: true })];
        _reasons_for_rejection_decorators = [(0, typeorm_1.ManyToMany)(function () { return reasons_for_rejection_entity_1.ReasonsForRejection; }, {
                eager: true,
                cascade: true,
            }), (0, typeorm_1.JoinTable)({ name: 'medicalReqs_reasonsForRejection' })];
        _motive_for_rejection_decorators = [(0, typeorm_1.JoinColumn)({
                name: 'motive_for_rejection',
                referencedColumnName: 'id',
            }), (0, typeorm_1.Column)({ type: 'integer', nullable: true, array: true })];
        _documents_delivered_decorators = [(0, typeorm_1.Column)({ type: 'text', array: true, nullable: true })];
        _delegate_id_decorators = [(0, typeorm_1.Column)({ type: 'uuid', nullable: true })];
        __esDecorate(null, null, _id_decorators, { kind: "field", name: "id", static: false, private: false, access: { has: function (obj) { return "id" in obj; }, get: function (obj) { return obj.id; }, set: function (obj, value) { obj.id = value; } }, metadata: _metadata }, _id_initializers, _id_extraInitializers);
        __esDecorate(null, null, _filing_number_decorators, { kind: "field", name: "filing_number", static: false, private: false, access: { has: function (obj) { return "filing_number" in obj; }, get: function (obj) { return obj.filing_number; }, set: function (obj, value) { obj.filing_number = value; } }, metadata: _metadata }, _filing_number_initializers, _filing_number_extraInitializers);
        __esDecorate(null, null, _req_type_decorators, { kind: "field", name: "req_type", static: false, private: false, access: { has: function (obj) { return "req_type" in obj; }, get: function (obj) { return obj.req_type; }, set: function (obj, value) { obj.req_type = value; } }, metadata: _metadata }, _req_type_initializers, _req_type_extraInitializers);
        __esDecorate(null, null, _requirement_type_decorators, { kind: "field", name: "requirement_type", static: false, private: false, access: { has: function (obj) { return "requirement_type" in obj; }, get: function (obj) { return obj.requirement_type; }, set: function (obj, value) { obj.requirement_type = value; } }, metadata: _metadata }, _requirement_type_initializers, _requirement_type_extraInitializers);
        __esDecorate(null, null, _registration_dates_decorators, { kind: "field", name: "registration_dates", static: false, private: false, access: { has: function (obj) { return "registration_dates" in obj; }, get: function (obj) { return obj.registration_dates; }, set: function (obj, value) { obj.registration_dates = value; } }, metadata: _metadata }, _registration_dates_initializers, _registration_dates_extraInitializers);
        __esDecorate(null, null, _right_petition_decorators, { kind: "field", name: "right_petition", static: false, private: false, access: { has: function (obj) { return "right_petition" in obj; }, get: function (obj) { return obj.right_petition; }, set: function (obj, value) { obj.right_petition = value; } }, metadata: _metadata }, _right_petition_initializers, _right_petition_extraInitializers);
        __esDecorate(null, null, _copy_right_petition_decorators, { kind: "field", name: "copy_right_petition", static: false, private: false, access: { has: function (obj) { return "copy_right_petition" in obj; }, get: function (obj) { return obj.copy_right_petition; }, set: function (obj, value) { obj.copy_right_petition = value; } }, metadata: _metadata }, _copy_right_petition_initializers, _copy_right_petition_extraInitializers);
        __esDecorate(null, null, _medicalReqUserType_decorators, { kind: "field", name: "medicalReqUserType", static: false, private: false, access: { has: function (obj) { return "medicalReqUserType" in obj; }, get: function (obj) { return obj.medicalReqUserType; }, set: function (obj, value) { obj.medicalReqUserType = value; } }, metadata: _metadata }, _medicalReqUserType_initializers, _medicalReqUserType_extraInitializers);
        __esDecorate(null, null, _familiar_decorators, { kind: "field", name: "familiar", static: false, private: false, access: { has: function (obj) { return "familiar" in obj; }, get: function (obj) { return obj.familiar; }, set: function (obj, value) { obj.familiar = value; } }, metadata: _metadata }, _familiar_initializers, _familiar_extraInitializers);
        __esDecorate(null, null, _familiar_id_decorators, { kind: "field", name: "familiar_id", static: false, private: false, access: { has: function (obj) { return "familiar_id" in obj; }, get: function (obj) { return obj.familiar_id; }, set: function (obj, value) { obj.familiar_id = value; } }, metadata: _metadata }, _familiar_id_initializers, _familiar_id_extraInitializers);
        __esDecorate(null, null, _aplicantId_decorators, { kind: "field", name: "aplicantId", static: false, private: false, access: { has: function (obj) { return "aplicantId" in obj; }, get: function (obj) { return obj.aplicantId; }, set: function (obj, value) { obj.aplicantId = value; } }, metadata: _metadata }, _aplicantId_initializers, _aplicantId_extraInitializers);
        __esDecorate(null, null, _patient_class_decorators, { kind: "field", name: "patient_class", static: false, private: false, access: { has: function (obj) { return "patient_class" in obj; }, get: function (obj) { return obj.patient_class; }, set: function (obj, value) { obj.patient_class = value; } }, metadata: _metadata }, _patient_class_initializers, _patient_class_extraInitializers);
        __esDecorate(null, null, _patient_class_status_decorators, { kind: "field", name: "patient_class_status", static: false, private: false, access: { has: function (obj) { return "patient_class_status" in obj; }, get: function (obj) { return obj.patient_class_status; }, set: function (obj, value) { obj.patient_class_status = value; } }, metadata: _metadata }, _patient_class_status_initializers, _patient_class_status_extraInitializers);
        __esDecorate(null, null, _relationship_with_patient_decorators, { kind: "field", name: "relationship_with_patient", static: false, private: false, access: { has: function (obj) { return "relationship_with_patient" in obj; }, get: function (obj) { return obj.relationship_with_patient; }, set: function (obj, value) { obj.relationship_with_patient = value; } }, metadata: _metadata }, _relationship_with_patient_initializers, _relationship_with_patient_extraInitializers);
        __esDecorate(null, null, _patient_name_decorators, { kind: "field", name: "patient_name", static: false, private: false, access: { has: function (obj) { return "patient_name" in obj; }, get: function (obj) { return obj.patient_name; }, set: function (obj, value) { obj.patient_name = value; } }, metadata: _metadata }, _patient_name_initializers, _patient_name_extraInitializers);
        __esDecorate(null, null, _patient_id_type_decorators, { kind: "field", name: "patient_id_type", static: false, private: false, access: { has: function (obj) { return "patient_id_type" in obj; }, get: function (obj) { return obj.patient_id_type; }, set: function (obj, value) { obj.patient_id_type = value; } }, metadata: _metadata }, _patient_id_type_initializers, _patient_id_type_extraInitializers);
        __esDecorate(null, null, _patient_id_number_decorators, { kind: "field", name: "patient_id_number", static: false, private: false, access: { has: function (obj) { return "patient_id_number" in obj; }, get: function (obj) { return obj.patient_id_number; }, set: function (obj, value) { obj.patient_id_number = value; } }, metadata: _metadata }, _patient_id_number_initializers, _patient_id_number_extraInitializers);
        __esDecorate(null, null, _aplicant_name_decorators, { kind: "field", name: "aplicant_name", static: false, private: false, access: { has: function (obj) { return "aplicant_name" in obj; }, get: function (obj) { return obj.aplicant_name; }, set: function (obj, value) { obj.aplicant_name = value; } }, metadata: _metadata }, _aplicant_name_initializers, _aplicant_name_extraInitializers);
        __esDecorate(null, null, _aplicant_last_name_decorators, { kind: "field", name: "aplicant_last_name", static: false, private: false, access: { has: function (obj) { return "aplicant_last_name" in obj; }, get: function (obj) { return obj.aplicant_last_name; }, set: function (obj, value) { obj.aplicant_last_name = value; } }, metadata: _metadata }, _aplicant_last_name_initializers, _aplicant_last_name_extraInitializers);
        __esDecorate(null, null, _aplicant_gender_decorators, { kind: "field", name: "aplicant_gender", static: false, private: false, access: { has: function (obj) { return "aplicant_gender" in obj; }, get: function (obj) { return obj.aplicant_gender; }, set: function (obj, value) { obj.aplicant_gender = value; } }, metadata: _metadata }, _aplicant_gender_initializers, _aplicant_gender_extraInitializers);
        __esDecorate(null, null, _aplicant_id_type_decorators, { kind: "field", name: "aplicant_id_type", static: false, private: false, access: { has: function (obj) { return "aplicant_id_type" in obj; }, get: function (obj) { return obj.aplicant_id_type; }, set: function (obj, value) { obj.aplicant_id_type = value; } }, metadata: _metadata }, _aplicant_id_type_initializers, _aplicant_id_type_extraInitializers);
        __esDecorate(null, null, _aplicant_id_number_decorators, { kind: "field", name: "aplicant_id_number", static: false, private: false, access: { has: function (obj) { return "aplicant_id_number" in obj; }, get: function (obj) { return obj.aplicant_id_number; }, set: function (obj, value) { obj.aplicant_id_number = value; } }, metadata: _metadata }, _aplicant_id_number_initializers, _aplicant_id_number_extraInitializers);
        __esDecorate(null, null, _aplicant_email_decorators, { kind: "field", name: "aplicant_email", static: false, private: false, access: { has: function (obj) { return "aplicant_email" in obj; }, get: function (obj) { return obj.aplicant_email; }, set: function (obj, value) { obj.aplicant_email = value; } }, metadata: _metadata }, _aplicant_email_initializers, _aplicant_email_extraInitializers);
        __esDecorate(null, null, _aplicant_cellphone_decorators, { kind: "field", name: "aplicant_cellphone", static: false, private: false, access: { has: function (obj) { return "aplicant_cellphone" in obj; }, get: function (obj) { return obj.aplicant_cellphone; }, set: function (obj, value) { obj.aplicant_cellphone = value; } }, metadata: _metadata }, _aplicant_cellphone_initializers, _aplicant_cellphone_extraInitializers);
        __esDecorate(null, null, _aplicant_eps_company_decorators, { kind: "field", name: "aplicant_eps_company", static: false, private: false, access: { has: function (obj) { return "aplicant_eps_company" in obj; }, get: function (obj) { return obj.aplicant_eps_company; }, set: function (obj, value) { obj.aplicant_eps_company = value; } }, metadata: _metadata }, _aplicant_eps_company_initializers, _aplicant_eps_company_extraInitializers);
        __esDecorate(null, null, _aplicant_company_area_decorators, { kind: "field", name: "aplicant_company_area", static: false, private: false, access: { has: function (obj) { return "aplicant_company_area" in obj; }, get: function (obj) { return obj.aplicant_company_area; }, set: function (obj, value) { obj.aplicant_company_area = value; } }, metadata: _metadata }, _aplicant_company_area_initializers, _aplicant_company_area_extraInitializers);
        __esDecorate(null, null, _accept_terms_decorators, { kind: "field", name: "accept_terms", static: false, private: false, access: { has: function (obj) { return "accept_terms" in obj; }, get: function (obj) { return obj.accept_terms; }, set: function (obj, value) { obj.accept_terms = value; } }, metadata: _metadata }, _accept_terms_initializers, _accept_terms_extraInitializers);
        __esDecorate(null, null, _copy_applicant_identification_document_decorators, { kind: "field", name: "copy_applicant_identification_document", static: false, private: false, access: { has: function (obj) { return "copy_applicant_identification_document" in obj; }, get: function (obj) { return obj.copy_applicant_identification_document; }, set: function (obj, value) { obj.copy_applicant_identification_document = value; } }, metadata: _metadata }, _copy_applicant_identification_document_initializers, _copy_applicant_identification_document_extraInitializers);
        __esDecorate(null, null, _copy_patient_citizenship_card_decorators, { kind: "field", name: "copy_patient_citizenship_card", static: false, private: false, access: { has: function (obj) { return "copy_patient_citizenship_card" in obj; }, get: function (obj) { return obj.copy_patient_citizenship_card; }, set: function (obj, value) { obj.copy_patient_citizenship_card = value; } }, metadata: _metadata }, _copy_patient_citizenship_card_initializers, _copy_patient_citizenship_card_extraInitializers);
        __esDecorate(null, null, _copy_patient_civil_registration_decorators, { kind: "field", name: "copy_patient_civil_registration", static: false, private: false, access: { has: function (obj) { return "copy_patient_civil_registration" in obj; }, get: function (obj) { return obj.copy_patient_civil_registration; }, set: function (obj, value) { obj.copy_patient_civil_registration = value; } }, metadata: _metadata }, _copy_patient_civil_registration_initializers, _copy_patient_civil_registration_extraInitializers);
        __esDecorate(null, null, _copy_parents_citizenship_card_decorators, { kind: "field", name: "copy_parents_citizenship_card", static: false, private: false, access: { has: function (obj) { return "copy_parents_citizenship_card" in obj; }, get: function (obj) { return obj.copy_parents_citizenship_card; }, set: function (obj, value) { obj.copy_parents_citizenship_card = value; } }, metadata: _metadata }, _copy_parents_citizenship_card_initializers, _copy_parents_citizenship_card_extraInitializers);
        __esDecorate(null, null, _copy_marriage_certificate_decorators, { kind: "field", name: "copy_marriage_certificate", static: false, private: false, access: { has: function (obj) { return "copy_marriage_certificate" in obj; }, get: function (obj) { return obj.copy_marriage_certificate; }, set: function (obj, value) { obj.copy_marriage_certificate = value; } }, metadata: _metadata }, _copy_marriage_certificate_initializers, _copy_marriage_certificate_extraInitializers);
        __esDecorate(null, null, _copy_cohabitation_certificate_decorators, { kind: "field", name: "copy_cohabitation_certificate", static: false, private: false, access: { has: function (obj) { return "copy_cohabitation_certificate" in obj; }, get: function (obj) { return obj.copy_cohabitation_certificate; }, set: function (obj, value) { obj.copy_cohabitation_certificate = value; } }, metadata: _metadata }, _copy_cohabitation_certificate_initializers, _copy_cohabitation_certificate_extraInitializers);
        __esDecorate(null, null, _date_of_admission_decorators, { kind: "field", name: "date_of_admission", static: false, private: false, access: { has: function (obj) { return "date_of_admission" in obj; }, get: function (obj) { return obj.date_of_admission; }, set: function (obj, value) { obj.date_of_admission = value; } }, metadata: _metadata }, _date_of_admission_initializers, _date_of_admission_extraInitializers);
        __esDecorate(null, null, _answer_date_decorators, { kind: "field", name: "answer_date", static: false, private: false, access: { has: function (obj) { return "answer_date" in obj; }, get: function (obj) { return obj.answer_date; }, set: function (obj, value) { obj.answer_date = value; } }, metadata: _metadata }, _answer_date_initializers, _answer_date_extraInitializers);
        __esDecorate(null, null, _response_time_decorators, { kind: "field", name: "response_time", static: false, private: false, access: { has: function (obj) { return "response_time" in obj; }, get: function (obj) { return obj.response_time; }, set: function (obj, value) { obj.response_time = value; } }, metadata: _metadata }, _response_time_initializers, _response_time_extraInitializers);
        __esDecorate(null, null, _download_expiration_date_decorators, { kind: "field", name: "download_expiration_date", static: false, private: false, access: { has: function (obj) { return "download_expiration_date" in obj; }, get: function (obj) { return obj.download_expiration_date; }, set: function (obj, value) { obj.download_expiration_date = value; } }, metadata: _metadata }, _download_expiration_date_initializers, _download_expiration_date_extraInitializers);
        __esDecorate(null, null, _is_deleted_decorators, { kind: "field", name: "is_deleted", static: false, private: false, access: { has: function (obj) { return "is_deleted" in obj; }, get: function (obj) { return obj.is_deleted; }, set: function (obj, value) { obj.is_deleted = value; } }, metadata: _metadata }, _is_deleted_initializers, _is_deleted_extraInitializers);
        __esDecorate(null, null, _createdAt_decorators, { kind: "field", name: "createdAt", static: false, private: false, access: { has: function (obj) { return "createdAt" in obj; }, get: function (obj) { return obj.createdAt; }, set: function (obj, value) { obj.createdAt = value; } }, metadata: _metadata }, _createdAt_initializers, _createdAt_extraInitializers);
        __esDecorate(null, null, _updateAt_decorators, { kind: "field", name: "updateAt", static: false, private: false, access: { has: function (obj) { return "updateAt" in obj; }, get: function (obj) { return obj.updateAt; }, set: function (obj, value) { obj.updateAt = value; } }, metadata: _metadata }, _updateAt_initializers, _updateAt_extraInitializers);
        __esDecorate(null, null, _deletedAt_decorators, { kind: "field", name: "deletedAt", static: false, private: false, access: { has: function (obj) { return "deletedAt" in obj; }, get: function (obj) { return obj.deletedAt; }, set: function (obj, value) { obj.deletedAt = value; } }, metadata: _metadata }, _deletedAt_initializers, _deletedAt_extraInitializers);
        __esDecorate(null, null, _is_it_reviewed_decorators, { kind: "field", name: "is_it_reviewed", static: false, private: false, access: { has: function (obj) { return "is_it_reviewed" in obj; }, get: function (obj) { return obj.is_it_reviewed; }, set: function (obj, value) { obj.is_it_reviewed = value; } }, metadata: _metadata }, _is_it_reviewed_initializers, _is_it_reviewed_extraInitializers);
        __esDecorate(null, null, _aplicant_decorators, { kind: "field", name: "aplicant", static: false, private: false, access: { has: function (obj) { return "aplicant" in obj; }, get: function (obj) { return obj.aplicant; }, set: function (obj, value) { obj.aplicant = value; } }, metadata: _metadata }, _aplicant_initializers, _aplicant_extraInitializers);
        __esDecorate(null, null, _review_area_decorators, { kind: "field", name: "review_area", static: false, private: false, access: { has: function (obj) { return "review_area" in obj; }, get: function (obj) { return obj.review_area; }, set: function (obj, value) { obj.review_area = value; } }, metadata: _metadata }, _review_area_initializers, _review_area_extraInitializers);
        __esDecorate(null, null, _currently_in_area_decorators, { kind: "field", name: "currently_in_area", static: false, private: false, access: { has: function (obj) { return "currently_in_area" in obj; }, get: function (obj) { return obj.currently_in_area; }, set: function (obj, value) { obj.currently_in_area = value; } }, metadata: _metadata }, _currently_in_area_initializers, _currently_in_area_extraInitializers);
        __esDecorate(null, null, _area_redirection_message_decorators, { kind: "field", name: "area_redirection_message", static: false, private: false, access: { has: function (obj) { return "area_redirection_message" in obj; }, get: function (obj) { return obj.area_redirection_message; }, set: function (obj, value) { obj.area_redirection_message = value; } }, metadata: _metadata }, _area_redirection_message_initializers, _area_redirection_message_extraInitializers);
        __esDecorate(null, null, _req_status_decorators, { kind: "field", name: "req_status", static: false, private: false, access: { has: function (obj) { return "req_status" in obj; }, get: function (obj) { return obj.req_status; }, set: function (obj, value) { obj.req_status = value; } }, metadata: _metadata }, _req_status_initializers, _req_status_extraInitializers);
        __esDecorate(null, null, _requirement_status_decorators, { kind: "field", name: "requirement_status", static: false, private: false, access: { has: function (obj) { return "requirement_status" in obj; }, get: function (obj) { return obj.requirement_status; }, set: function (obj, value) { obj.requirement_status = value; } }, metadata: _metadata }, _requirement_status_initializers, _requirement_status_extraInitializers);
        __esDecorate(null, null, _user_message_decorators, { kind: "field", name: "user_message", static: false, private: false, access: { has: function (obj) { return "user_message" in obj; }, get: function (obj) { return obj.user_message; }, set: function (obj, value) { obj.user_message = value; } }, metadata: _metadata }, _user_message_initializers, _user_message_extraInitializers);
        __esDecorate(null, null, _user_message_documents_decorators, { kind: "field", name: "user_message_documents", static: false, private: false, access: { has: function (obj) { return "user_message_documents" in obj; }, get: function (obj) { return obj.user_message_documents; }, set: function (obj, value) { obj.user_message_documents = value; } }, metadata: _metadata }, _user_message_documents_initializers, _user_message_documents_extraInitializers);
        __esDecorate(null, null, _response_comments_decorators, { kind: "field", name: "response_comments", static: false, private: false, access: { has: function (obj) { return "response_comments" in obj; }, get: function (obj) { return obj.response_comments; }, set: function (obj, value) { obj.response_comments = value; } }, metadata: _metadata }, _response_comments_initializers, _response_comments_extraInitializers);
        __esDecorate(null, null, _reasons_for_rejection_decorators, { kind: "field", name: "reasons_for_rejection", static: false, private: false, access: { has: function (obj) { return "reasons_for_rejection" in obj; }, get: function (obj) { return obj.reasons_for_rejection; }, set: function (obj, value) { obj.reasons_for_rejection = value; } }, metadata: _metadata }, _reasons_for_rejection_initializers, _reasons_for_rejection_extraInitializers);
        __esDecorate(null, null, _motive_for_rejection_decorators, { kind: "field", name: "motive_for_rejection", static: false, private: false, access: { has: function (obj) { return "motive_for_rejection" in obj; }, get: function (obj) { return obj.motive_for_rejection; }, set: function (obj, value) { obj.motive_for_rejection = value; } }, metadata: _metadata }, _motive_for_rejection_initializers, _motive_for_rejection_extraInitializers);
        __esDecorate(null, null, _documents_delivered_decorators, { kind: "field", name: "documents_delivered", static: false, private: false, access: { has: function (obj) { return "documents_delivered" in obj; }, get: function (obj) { return obj.documents_delivered; }, set: function (obj, value) { obj.documents_delivered = value; } }, metadata: _metadata }, _documents_delivered_initializers, _documents_delivered_extraInitializers);
        __esDecorate(null, null, _delegate_id_decorators, { kind: "field", name: "delegate_id", static: false, private: false, access: { has: function (obj) { return "delegate_id" in obj; }, get: function (obj) { return obj.delegate_id; }, set: function (obj, value) { obj.delegate_id = value; } }, metadata: _metadata }, _delegate_id_initializers, _delegate_id_extraInitializers);
        __esDecorate(null, _classDescriptor = { value: _classThis }, _classDecorators, { kind: "class", name: _classThis.name, metadata: _metadata }, null, _classExtraInitializers);
        MedicalReq = _classThis = _classDescriptor.value;
        if (_metadata) Object.defineProperty(_classThis, Symbol.metadata, { enumerable: true, configurable: true, writable: true, value: _metadata });
        __runInitializers(_classThis, _classExtraInitializers);
    })();
    return MedicalReq = _classThis;
}();
exports.MedicalReq = MedicalReq;
