export enum RequirementTypeEnum {
  CLINIC_HISTORY = 'HISTORIA CLÍNICA',
  MEDICAL_ORDER = 'ORDEN MÉDICA',
  CERTIFICATE_OF_MEDICAL_DISABILITY = 'CERTIFICADO DE INCAPACIDAD MÉDICA',
  MIPRES_EXTERNAL_CONSULTATION = 'MIPRES CONSULTA EXTERNA',
}
